### ISSUE TITLE
Data for trial run

### ISSUE THREAD

**Issue by shere-khan** [youngmki/musinsaigo#1]
Hey,

Big thanks for posting this code. There aren't many examples of getting SDXL to run in SageMaker online. I've been making my way through the repo code, but it's tough to figure out the config.yaml file because I don't know what all the variables mean, so I'm making my way through aws docs at the same time...

1) Can you send me an example of how your original dataset was formatted before it gets captioned via CLIP?

**EDIT**
I think I see. sdxl_lora/trian.py is just expecting the traditional DataLoader format
dataset_dir/
    train/
        image1.jpg
        image2.jpg
        ...
    val/
        image1.jpg
        image2.jpg
        ...
        
I'm trying to run lora finetuning. I have a data set that has no text captions and I would like to add them. Is it formatted in the way a traditional DataLoader expects the data, like "data/image-1.png", ..., "data/image-n.png"? It seems like the model takes images with no captions, spins up an instance based on an image that uses CLIP to create captions for the images, then spins up an instance based on another image that does the training. It looks like the DataLoader is in sd_lora/train.py

2) Also, what would be the best way to load the baseline sdxl v1 from HF so I can finetune using lora using those pretrained weights?
https://huggingface.co/stabilityai/stable-diffusion-xl-base-1.0

I'm really experienced with SM notebooks, but I haven't containerized anything and leverage training jobs yet via sagemaker sdk code yet. So I'm learning.

Best regards,
JB

**Comment by shere-khan** [comment]
FYI I figured this all out. Still trying to get the code to run in sagemaker. Did you all get all of your Dockerfiles and everything to work? I can't even run docker from a sagemaker notebook. I have to use `sm-docker build`. Do you have any advice or specs/configs for your environment?

**Comment by youngmki** [comment]
Hello, it's been a while since you asked your question, so I don't know if you need my answer.

1. I used a multimodal model called ['InstructBlip'](https://arxiv.org/abs/2305.06500) for captioning images crawled from the internet for Stable Diffusion model fine-tuning. The code is in the 'code/data_prep/image_caption.py' file.

The caption file was named 'metadata.jsonl' and saved in the same directory as the images. The format of that file is shown below. 

{"file_name": "image1.png", "text": "caption..."}
{"file_name": "image2.png", "text": "caption..."}
...

2. I built and pushed Docker files from my local environment and ran the SageMaker container-based codes in my local IDE (PyCharm).

**Comment by shere-khan** [comment]
Ah okay, so you're running locally. I couldn't get the docker builds to work in sagemaker studio. Let me give that a shot locally and report back. Thanks
